# Generated by Django 5.2 on 2025-04-19 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="datetime",
            new_name="sale_date",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="price",
        ),
        migrations.RemoveField(
            model_name="saleitem",
            name="price_at_sale",
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="shelf_location",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="pharmacy.sale",
            ),
        ),
    ]
