# Generated by Django 5.2 on 2025-04-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pharmacy",
            "0002_rename_datetime_sale_sale_date_remove_medicine_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="price",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
